# Application
APPS=(
    ARDOP=/$HOME/scripts/ardop.sh
BBS-Client=/$HOME/scripts/bbs-client.sh
BBB-Server=/$HOME/scripts/bbs-server.sh
Min-browser=/$HOME/scripts/min.sh
CAT=/$HOME/scripts/cat.sh
Chattervox=/$HOME/scripts/chattervox.sh
Direwolf=/$HOME/scripts/direwolf.sh
GPS=/$HOME/scripts/gps.sh
Hamlib=/$HOME/scripts/hamlib.sh
JS8Call=/$HOME/scripts/js8call.sh
Navit=/$HOME/scripts/navit.sh
AX-25=/$HOME/scripts/ax-25.sh
Pup=/$HOME/scripts/pup.sh
Qttermtcp=/$HOME/scripts/qttermtcp.sh
Wine=/$HOME/scripts/wine.sh
Winlink=/$HOME/scripts/winlink.sh
Wikipedia=/$HOME/scripts/wikipedia.sh
)
