# Applicatiion Dependencies
DEPEND=(
  build-essential \
  cmake \
  curl \
  gpg \
  imagemagick \
  jq \
  net-tools \
  openjdk-20-jdk \
  openssh-server \
  screen \
  socat \
  steghide \
  stow \
  xsel \
  tree \
  audacity \
  ffmpeg \
  sox \
  qtbase5-dev:i386 \
  qtbase5-dev-tools:i386 \
  qt5-qmake:i386 \
  qtchooser:i386 \
  qtmultimedia5-dev:i386 \
  libqt5serialport5-dev:i386 \
  libfftw3-dev:i386 \
  qttools5-dev-tools:i386 \
  qtbase5-dev:i386 \
  qtbase5-dev-tools:i386 \
  qt5-qmake:i386 \
  qtchooser:i386 \
  qtmultimedia5-dev:i386 \
  libqt5serialport5-dev:i386 \
  libfftw3-dev:i386 \
  qttools5-dev-tools:i386 \
  qtbase5-dev \
  qtbase5-dev-tools \
  qt5-qmake \
  qtchooser \
  qtmultimedia5-dev \
  libqt5serialport5-dev \
  libfftw3-dev \
  qttools5-dev-tools \
  ax25-tools \
  ax25-apps \
  expect \
  libqt5serialport5 \
  libqt5multimedia5-plugins \
  libqt5widgets5 \
  libqt5multimediawidgets5 \
  libqt5core5a \
  libqt5gui5 \
  libqt5multimedia5 \
  libqt5network5 \
  libqt5printsupport5 \
  libqt5serialport5 \
  libqt5widgets5 \
  libdouble-conversion3 \
  libpcre2-16-0 \
  qttranslations5-l10n \
  libmd4c0 \
  libqt5dbus5 \
  libxcb-xinerama0 \
  libxcb-xinput0 \
  libqt5svg5 \
  qt5-gtk-platformtheme \
  libqt5multimediagsttools5 \
  libgfortran5 \
  qtbase5-dev \
  qtbase5-dev-tools \
  qt5-qmake \
  qtchooser \
  qtmultimedia5-dev \
  libqt5serialport5-dev \
  libfftw3-dev \
  qttools5-dev-tools \
  gpsd \
  gpsd-clients \
  gpsd-tools \
  chrony \
  at \
  gcc \
  g++ \
  make \
  cmake \
  libasound2-dev \
  libudev-dev \
  autoconf \
  dialog \
  gettext \
  libfltk1.3-dev \
  libportaudio2 \
  libsamplerate0-dev \
  libsndfile1-dev \
  libudev-dev \
  pkg-config \
  portaudio19-dev \
  conky \
  python3 \
  -y
)